server:
  port: 19092

spring:
  application:
    name: tms-service

  datasource:
    #url: jdbc:mysql://localhost:3306/tms
    url: jdbc:mysql://host.docker.internal:3306/tms #도커 컴포즈로 띄우기 위한 설정
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true


jwt:
  secret:
    key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"


eureka:
  client:
    service-url:
      #defaultZone: http://localhost:19090/eureka/
      defaultZone: http://eureka:19090/eureka/ #도커 컴포즈로 띄우기 위한 설정


gemini:
  api:
    url: "https://generativelanguage.googleapis.com/v1/models/gemini-pro:generateContent"
    key: ${GEMINI_KEY}

public:
  portal:
    url: "http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst"
    key: ${PUBLIC_PORTAL_KEY}

slack:
  api:
    url: "https://slack.com/api/chat.postMessage"
    token: ${SLACK_TOKEN}