server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**,/users/**,/delivery-users/**
        - id: tms-service
          uri: lb://tms-service
          predicates:
            - Path=/hubs/**,/stores/**,/products/**,/orders/**

      discovery:
        locator:
          enabled: true


eureka:
  client:
    service-url:
      #defaultZone: http://localhost:19090/eureka/
      defaultZone: http://eureka:19090/eureka/ #도커 컴포즈로 띄우기 위한 설정


jwt:
  secret:
    key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"
